spring:
  config:
    import: classpath:/properties/env.yml #ADMIN의 username과 password, EUREKA url, GITHUB repo의 ssh 주소와 private key

  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: ${github.uri}
          ignore-local-ssh-settings: true
          private-key: ${github.private-key}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka.server}

server:
  port: 9000
  username: ${server.username}
  password: ${server.password}