spring:
  config:
    import: classpath:/properties/env.yml

  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: ${github.uri}
          ignore-local-ssh-settings: true
          private-key: ${github.private-key}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka.server}

server:
  port: 9000